name: openssl

on: [push]

jobs:
  mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install curl zip unzip gnu-sed erlang openssl@1.1
        echo "/usr/local/bin:$PATH" >> ~/.bashrc
    - name: openssl version
      run: |
        cc   -I"/usr/local/Cellar/erlang@21/21.3.8/lib/erlang/lib/erl_interface-3.11.3/include" -I"/usr/local/Cellar/erlang@21/21.3.8/lib/erlang/erts-10.3.5/include"    -L"/usr/local/Cellar/erlang@21/21.3.8/lib/erlang/lib/erl_interface-3.11.3/lib" -lerl_interface -lei bcrypt_port.c bcrypt.o blowfish.o   -L"/usr/local/Cellar/erlang@21/21.3.8/lib/erlang/lib/erl_interface-3.11.3/lib" -lerl_interface -lei -lpthread -o ../priv/bcrypt
    - name: build
      run: |
        version=$(echo ${{ github.ref }} | gsed -r  "s .*/.*/(.*) \1 g")
        version=develop
        EMQX_DEPS_DEFAULT_VSN=$version make emqx
        mkdir -p _packages/emqx
        cd ./_build/emqx/rel && zip -rq emqx-macosx-$version.zip emqx && cd - && mv ./_build/emqx/rel/emqx-macosx-$version.zip _packages/emqx
        cd ./_build/emqx/rel/emqx && otool -L lib/crypto-*/priv/lib/crypto.so
    - uses: actions/upload-artifact@v1
      with:
        name: emqx-macosx
        path: _packages/emqx