name: Run paho tests

on: 
  push:
    tags:
      - v*
  repository_dispatch:
    types: [run_tests]

jobs:

    run_paho_tests:

        runs-on: ubuntu-latest

        steps:
        - name: Install docker-compose
          run: | 
            sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
        - uses: actions/checkout@v1
        - name: set env
          run: |
            if [ ${{ github.event_name}} == 'repository_dispatch' ]; then version=${{ github.event.client_payload.version }}; else version=$(echo ${{ github.ref }} | sed -r  "s .*/.*/(.*) \1 g"); fi
            echo "version=$version" >> $GITHUB_ENV
            if [ ! -z $(echo $version | grep -oE "v[0-9]+\.[0-9]+(\.[0-9]+)?") ]; then
              echo "EMQX_DEPS_DEFAULT_VSN=$version" >> $GITHUB_ENV
            fi
        - name: get deps
          run: make deps-emqx
        - name: make emqx image
          run: make emqx-docker-build
        - name: make paho tests
          run: TARGET=emqx/emqx PAHO_BRANCH="develop-4.0" make -C .ci/paho_tests test
